org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableJetifier=true
org.gradle.java.home=C\:\\Users\\m3kwm\\Downloads\\Procreate_Android_Workspace-20260910T204503Z-1-001\\Procreate_Android_Workspace\\jdk\\zulu17.48.15-ca-jdk17.0.10-win_x64

systemProp.org.gradle.internal.http.connectionTimeout=300000
systemProp.org.gradle.internal.http.socketTimeout=300000
