#!/usr/bin/env python3
"""
Artify Texture Lab: original, reproducible brush shapes and paper grains (Phase 0A2).

Every image is synthesised from seeded noise and geometry in this file, so its provenance is simply
"generated by Artify's own code". Nothing is traced, sampled or derived from a third-party image.
The same seed always produces byte-identical output, which lets reviewers diff textures by hash.

Formats match what BrushTextures.kt already consumes, so no engine change is needed to try them:
  * shapes/  : white ink on black, luminance = ink amount   (createCustomTip reads lum * alpha)
  * grains/  : grey heightmap, contrast-stretched to alpha   (getGrainTextureCustom)
               grains are exactly periodic, so the tile repeats with no visible seam.

Usage:
    python3 tools/texture_lab/generate_textures.py            # -> tools/texture_lab/output/
    python3 tools/texture_lab/generate_textures.py --sheet docs/provenance/texture-lab-sheet.png

Requires numpy and Pillow. Output is not copied into app/ automatically: the product owner
approves the look first, then the Executor wires approved files per PHASE-0A2.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

SIZE = 512
ROOT = Path(__file__).resolve().parent
DEFAULT_OUT = ROOT / "output"


# ----------------------------------------------------------------------------- noise primitives

def rng(seed: int) -> np.random.Generator:
    return np.random.default_rng(seed)


def periodic_noise(seed: int, beta: float, size: int = SIZE, anisotropy: float = 1.0) -> np.ndarray:
    """Spectral-synthesis noise with a 1/f^beta power law. Periodic by construction (FFT basis)."""
    white = rng(seed).standard_normal((size, size))
    fy = np.fft.fftfreq(size)[:, None]
    fx = np.fft.fftfreq(size)[None, :] * anisotropy
    radius = np.sqrt(fx * fx + fy * fy)
    radius[0, 0] = 1.0
    spectrum = np.fft.fft2(white) / radius ** (beta / 2.0)
    spectrum[0, 0] = 0.0
    field = np.real(np.fft.ifft2(spectrum))
    return normalise(field)


def normalise(a: np.ndarray) -> np.ndarray:
    lo, hi = np.percentile(a, 0.5), np.percentile(a, 99.5)
    return np.clip((a - lo) / max(hi - lo, 1e-9), 0.0, 1.0)


def radial(size: int = SIZE) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    y, x = np.mgrid[0:size, 0:size].astype(np.float64)
    cx = cy = (size - 1) / 2.0
    dx, dy = (x - cx) / (size / 2.0), (y - cy) / (size / 2.0)
    return dx, dy, np.sqrt(dx * dx + dy * dy)


def smoothstep(edge0: float, edge1: float, x: np.ndarray) -> np.ndarray:
    t = np.clip((x - edge0) / (edge1 - edge0), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def to_image(a: np.ndarray) -> Image.Image:
    return Image.fromarray((np.clip(a, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8), mode="L")


# ----------------------------------------------------------------------------- grains (periodic)

def grain_cold_press(seed: int) -> np.ndarray:
    """Watercolour paper: broad hills plus fine tooth."""
    return normalise(0.65 * periodic_noise(seed, 2.6) + 0.35 * periodic_noise(seed + 1, 1.2))


def grain_hot_press(seed: int) -> np.ndarray:
    """Smooth pressed paper: faint, fine tooth only."""
    return 0.55 + 0.45 * periodic_noise(seed, 0.9) * 0.6


def grain_laid_paper(seed: int) -> np.ndarray:
    """Handmade laid paper: fine horizontal laid lines, sparse chain lines, fibre noise."""
    y, x = np.mgrid[0:SIZE, 0:SIZE]
    laid = 0.5 + 0.5 * np.cos(2 * np.pi * y / (SIZE / 64))          # 64 lines per tile, periodic
    chain = np.exp(-((np.minimum(x % (SIZE // 4), SIZE // 4 - x % (SIZE // 4))) / 2.2) ** 2)
    fibre = periodic_noise(seed, 1.6, anisotropy=0.35)
    return normalise(0.45 * fibre + 0.35 * laid - 0.25 * chain)


def grain_ahar_paper(seed: int) -> np.ndarray:
    """Burnished calligraphy paper (ahar): very smooth with long soft fibres and faint mottling."""
    fibres = periodic_noise(seed, 2.2, anisotropy=0.18)
    mottle = periodic_noise(seed + 7, 3.2)
    return 0.62 + 0.38 * normalise(0.55 * fibres + 0.45 * mottle) * 0.55


def grain_canvas_weave(seed: int) -> np.ndarray:
    """Linen canvas: two crossing thread sets with per-thread thickness variation."""
    y, x = np.mgrid[0:SIZE, 0:SIZE].astype(np.float64)
    threads = SIZE // 32  # integer thread pitch and an even count keep the weave periodic
    wobble_x = periodic_noise(seed, 3.0) * 1.6
    wobble_y = periodic_noise(seed + 1, 3.0) * 1.6
    warp = np.abs(np.sin(np.pi * (x + wobble_x) / threads))
    weft = np.abs(np.sin(np.pi * (y + wobble_y) / threads))
    over = (np.floor(x / threads) + np.floor(y / threads)) % 2
    weave = np.where(over == 0, warp * (0.6 + 0.4 * weft), weft * (0.6 + 0.4 * warp))
    return normalise(0.8 * weave + 0.2 * periodic_noise(seed + 2, 1.0))


def grain_charcoal_tooth(seed: int) -> np.ndarray:
    """Coarse drawing paper for charcoal: sharp peaks that catch pigment, deep valleys that don't."""
    base = periodic_noise(seed, 1.8)
    return np.clip((base - 0.35) / 0.5, 0.0, 1.0) ** 0.7


def grain_speckle(seed: int) -> np.ndarray:
    """Sparse random specks for dry media and stippled textures (periodic via wrap-around)."""
    field = np.full((SIZE, SIZE), 0.85)
    r = rng(seed)
    for _ in range(2600):
        cy, cx = r.integers(0, SIZE, size=2)
        radius = r.uniform(0.6, 2.4)
        span = int(np.ceil(radius)) + 1
        for dy in range(-span, span + 1):
            for dx in range(-span, span + 1):
                if dx * dx + dy * dy <= radius * radius:
                    field[(cy + dy) % SIZE, (cx + dx) % SIZE] = r.uniform(0.0, 0.35)
    return field


def grain_stained(seed: int) -> np.ndarray:
    """Aged paper with large soft tide-marks: low-frequency blotches with crisp contour edges."""
    blotch = periodic_noise(seed, 3.6)
    contours = np.abs(np.sin(blotch * np.pi * 5.0)) ** 8
    return normalise(0.75 * blotch - 0.25 * contours + 0.15 * periodic_noise(seed + 3, 1.1))


GRAINS = {
    "art-grain-cold-press": (grain_cold_press, 101),
    "art-grain-hot-press": (grain_hot_press, 102),
    "art-grain-laid-paper": (grain_laid_paper, 103),
    "art-grain-ahar-paper": (grain_ahar_paper, 104),
    "art-grain-canvas-weave": (grain_canvas_weave, 105),
    "art-grain-charcoal-tooth": (grain_charcoal_tooth, 106),
    "art-grain-speckle": (grain_speckle, 107),
    "art-grain-stained": (grain_stained, 108),
}


# ----------------------------------------------------------------------------- shapes (stamps)

def shape_soft_round(seed: int) -> np.ndarray:
    _, _, d = radial()
    return (1.0 - smoothstep(0.0, 0.98, d)) ** 1.6


def shape_ragged_round(seed: int) -> np.ndarray:
    """Hard round with an irregular, ink-bled rim."""
    dx, dy, d = radial()
    angle = np.arctan2(dy, dx)
    rim = 0.82 + 0.05 * np.sin(angle * 7 + seed) + 0.04 * (periodic_noise(seed, 2.0) - 0.5)
    return 1.0 - smoothstep(rim - 0.03, rim + 0.02, d)


def shape_charcoal_chunk(seed: int) -> np.ndarray:
    """Compressed charcoal side: a rough elongated block with pitted interior."""
    dx, dy, _ = radial()
    edge = np.maximum(np.abs(dx) / 0.9, np.abs(dy) / 0.42)
    body = 1.0 - smoothstep(0.78, 1.0, edge + 0.22 * (periodic_noise(seed, 1.7) - 0.5))
    pits = np.clip((periodic_noise(seed + 1, 1.3) - 0.2) / 0.6, 0.0, 1.0)
    return body * pits


def shape_dry_bristle(seed: int) -> np.ndarray:
    """Flat brush running nearly dry: separated bristle tracks of varying weight."""
    dx, dy, _ = radial()
    r = rng(seed)
    tracks = np.zeros((SIZE, SIZE))
    for _ in range(46):
        centre, width, weight = r.uniform(-0.85, 0.85), r.uniform(0.008, 0.03), r.uniform(0.3, 1.0)
        tracks = np.maximum(tracks, weight * np.exp(-((dy - centre) / width) ** 2))
    envelope = 1.0 - smoothstep(0.7, 0.95, np.abs(dx))
    breakup = np.clip((periodic_noise(seed + 2, 1.0, anisotropy=4.0) - 0.25) / 0.5, 0.0, 1.0)
    return tracks * envelope * breakup


def shape_spray(seed: int) -> np.ndarray:
    """Airbrush/spray: dense centre of fine droplets falling off with a Gaussian profile."""
    field = np.zeros((SIZE, SIZE))
    r = rng(seed)
    count = 5200
    radii = np.abs(r.normal(0.0, 0.34, count))
    angles = r.uniform(0.0, 2 * np.pi, count)
    for rad, ang in zip(radii, angles):
        if rad > 0.97:
            continue
        cx = int((0.5 + 0.5 * rad * np.cos(ang)) * (SIZE - 1))
        cy = int((0.5 + 0.5 * rad * np.sin(ang)) * (SIZE - 1))
        size = max(1, int(r.uniform(1.0, 3.2)))
        field[max(cy - size, 0):cy + size, max(cx - size, 0):cx + size] = r.uniform(0.55, 1.0)
    return field


def shape_splatter(seed: int) -> np.ndarray:
    """Ink splatter: a few drops with satellite droplets."""
    dx, dy, _ = radial()
    r = rng(seed)
    field = np.zeros((SIZE, SIZE))
    for _ in range(6):
        cx, cy, radius = r.uniform(-0.5, 0.5), r.uniform(-0.5, 0.5), r.uniform(0.08, 0.26)
        field = np.maximum(field, 1.0 - smoothstep(radius * 0.9, radius, np.hypot(dx - cx, dy - cy)))
        for _ in range(14):
            a, dist = r.uniform(0, 2 * np.pi), radius * r.uniform(1.2, 2.3)
            sx, sy, sr = cx + dist * np.cos(a), cy + dist * np.sin(a), radius * r.uniform(0.05, 0.18)
            field = np.maximum(field, 1.0 - smoothstep(sr * 0.8, sr, np.hypot(dx - sx, dy - sy)))
    return field


def shape_wet_blotch(seed: int) -> np.ndarray:
    """Watercolour bloom: pale interior with darker pigment gathered at the drying edge."""
    dx, dy, d = radial()
    wobble = 0.12 * (periodic_noise(seed, 2.8) - 0.5)
    rim = 0.78 + wobble
    inside = 1.0 - smoothstep(rim - 0.02, rim + 0.01, d)
    edge = np.exp(-((d - rim + 0.03) / 0.045) ** 2)
    return inside * (0.35 + 0.25 * periodic_noise(seed + 1, 2.0)) + 0.55 * edge * inside


def shape_qalam_nib(seed: int) -> np.ndarray:
    """Reed pen (qalam) contact: a thin slanted rectangle with a fibrous, slightly uneven edge."""
    dx, dy, _ = radial()
    theta = np.deg2rad(-35.0)
    u = dx * np.cos(theta) - dy * np.sin(theta)
    v = dx * np.sin(theta) + dy * np.cos(theta)
    fibre = 0.02 * (periodic_noise(seed, 1.4, anisotropy=6.0) - 0.5)
    body = (1.0 - smoothstep(0.84, 0.9, np.abs(u))) * (1.0 - smoothstep(0.12, 0.16, np.abs(v) + fibre))
    ink = 0.85 + 0.15 * periodic_noise(seed + 1, 1.0)
    return body * ink


def shape_distressed_stamp(seed: int) -> np.ndarray:
    """Worn rubber stamp: a square with eroded interior and chipped corners."""
    dx, dy, _ = radial()
    square = 1.0 - smoothstep(0.8, 0.84, np.maximum(np.abs(dx), np.abs(dy)))
    wear = np.clip((periodic_noise(seed, 1.5) - 0.28) / 0.35, 0.0, 1.0)
    chips = np.clip((periodic_noise(seed + 1, 3.0) - 0.15) / 0.2, 0.0, 1.0)
    return square * wear * chips


def shape_wax_crayon(seed: int) -> np.ndarray:
    """Wax crayon tip: rounded wedge whose ink skips over paper peaks."""
    dx, dy, _ = radial()
    body = 1.0 - smoothstep(0.7, 0.8, np.hypot(dx / 0.95, dy / 0.6))
    skip = np.clip((periodic_noise(seed, 1.1) - 0.3) / 0.4, 0.0, 1.0)
    return body * skip


SHAPES = {
    "art-shape-soft-round": (shape_soft_round, 201),
    "art-shape-ragged-round": (shape_ragged_round, 202),
    "art-shape-charcoal-chunk": (shape_charcoal_chunk, 203),
    "art-shape-dry-bristle": (shape_dry_bristle, 204),
    "art-shape-spray": (shape_spray, 205),
    "art-shape-splatter": (shape_splatter, 206),
    "art-shape-wet-blotch": (shape_wet_blotch, 207),
    "art-shape-qalam-nib": (shape_qalam_nib, 208),
    "art-shape-distressed-stamp": (shape_distressed_stamp, 209),
    "art-shape-wax-crayon": (shape_wax_crayon, 210),
}


# ----------------------------------------------------------------------------- output

def seam_error(a: np.ndarray) -> float:
    """
    Step across the tile's wrap edges divided by the step across its midlines, averaged over both
    axes. The midline shares the wrap edge's phase for any pattern whose period divides the tile, so
    a seamless tile scores about 1.0 and a visible seam scores well above it.
    """
    half = a.shape[0] // 2
    wrap = np.mean(np.abs(a[:, 0] - a[:, -1])) + np.mean(np.abs(a[0, :] - a[-1, :]))
    mid = np.mean(np.abs(a[:, half] - a[:, half - 1])) + np.mean(np.abs(a[half, :] - a[half - 1, :]))
    return float(wrap / max(mid, 1e-9))


def generate(out: Path) -> list[dict]:
    manifest = []
    for group, table in (("grains", GRAINS), ("shapes", SHAPES)):
        (out / group).mkdir(parents=True, exist_ok=True)
        for name, (fn, seed) in table.items():
            array = fn(seed)
            path = out / group / f"{name}.png"
            to_image(array).save(path, optimize=True)
            entry = {
                "file": f"{group}/{name}.png",
                "generator": fn.__name__,
                "seed": seed,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "provenance": "original: generated by tools/texture_lab/generate_textures.py",
            }
            if group == "grains":
                entry["seam_ratio"] = round(seam_error(array), 3)
            manifest.append(entry)
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def contact_sheet(out: Path, sheet: Path, tile: int = 160) -> None:
    files = sorted((out / "grains").glob("*.png")) + sorted((out / "shapes").glob("*.png"))
    columns = 6
    rows = (len(files) + columns - 1) // columns
    label_h = 18
    canvas = Image.new("L", (columns * tile, rows * (tile + label_h)), 24)
    draw = ImageDraw.Draw(canvas)
    font = ImageFont.load_default()
    for index, path in enumerate(files):
        x, y = (index % columns) * tile, (index // columns) * (tile + label_h)
        image = Image.open(path)
        if "grains" in path.parts:
            # Show grains tiled 2x2 so any seam would be visible in review.
            half = image.resize((tile // 2, tile // 2), Image.LANCZOS)
            for ox in (0, tile // 2):
                for oy in (0, tile // 2):
                    canvas.paste(half, (x + ox, y + oy))
        else:
            canvas.paste(image.resize((tile, tile), Image.LANCZOS), (x, y))
        draw.text((x + 4, y + tile + 3), path.stem.replace("art-", ""), fill=220, font=font)
    sheet.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(sheet, optimize=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--sheet", type=Path, help="also write a review contact sheet PNG")
    args = parser.parse_args()
    manifest = generate(args.out)
    if args.sheet:
        contact_sheet(args.out, args.sheet)
    print(f"Generated {len(manifest)} textures in {args.out}")
    for entry in manifest:
        seam = f"  seam={entry['seam_ratio']}" if "seam_ratio" in entry else ""
        print(f"  {entry['file']:44} {entry['sha256'][:12]}{seam}")


if __name__ == "__main__":
    main()
